/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author JUAN DAVID
 */
import co.edu.ufps.fortaleza.Fortaleza;
import java.awt.Color;

public class VistaGeneral extends javax.swing.JFrame {

    private VistaGeneral myP;
    private Fortaleza myControlador;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaGeneral.class.getName());

    /**
     * Creates new form VistaGeneral
     */
    public VistaGeneral() {
        initComponents();
        myControlador = new Fortaleza();
        habilitarPanel(this.panelProfesorCatedra, false);
        habilitarPanel(this.panelProfesorPlanta, false);
        habilitarPanel(this.panelProfesorOcasional, false);

        jPanel2.setBackground(Color.red);
    }

    public VistaGeneral getMyP() {
        return myP;
    }

    public Fortaleza getMyControlador() {
        return myControlador;
    }

    public void setMyControlador(Fortaleza myControlador) {
        this.myControlador = myControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelProfesorPlanta = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        spinnerFechaDeNombramiento = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        txtNumeroDeResolucionDeNombramiento = new javax.swing.JTextField();
        txtNumeroDePuntosSalariales = new javax.swing.JTextField();
        txtValorDelPuntoSalarial = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        btnGuardadPPlanta = new javax.swing.JButton();
        panelProfesorOcasional = new javax.swing.JPanel();
        btnGuardarPOcasional = new javax.swing.JButton();
        panelProfesorCatedra = new javax.swing.JPanel();
        txtNumeroDeContratoSemestral = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtValorHora = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNumeroDeHorasQueDictaPorSemana = new javax.swing.JTextField();
        btnGuardarPCatedra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaInformacion = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txCodigo = new javax.swing.JTextField();
        txtTituloAcademico = new javax.swing.JTextField();
        txtDepartamento = new javax.swing.JTextField();
        txtSalarioBasico = new javax.swing.JTextField();
        cmbTipoProfesor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnInfoDocentes = new javax.swing.JButton();
        btnSalarioDocentes = new javax.swing.JButton();
        btnVinculacionDocentes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        setPreferredSize(new java.awt.Dimension(64, 30));

        jPanel1.setLayout(new java.awt.CardLayout());

        panelProfesorPlanta.setBorder(javax.swing.BorderFactory.createTitledBorder("Profesor de Planta"));
        panelProfesorPlanta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setText("FECHA DE NOMBRAMIENTO");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setText("NUMERO DE RESOLUCION DE NOMBRAMIENTO");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setText("NUMERO DE PUNTOS SALARIALES");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setText("VALOR DEL PUNTO SALARIAL");
        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        spinnerFechaDeNombramiento.setModel(new javax.swing.SpinnerDateModel());

        jLabel13.setText("CATEGORIA");
        jLabel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNumeroDeResolucionDeNombramiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDeResolucionDeNombramientoActionPerformed(evt);
            }
        });

        txtNumeroDePuntosSalariales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDePuntosSalarialesActionPerformed(evt);
            }
        });

        txtValorDelPuntoSalarial.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnGuardadPPlanta.setText("GUARDAR");
        btnGuardadPPlanta.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnGuardadPPlanta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnGuardadPPlanta.setVerifyInputWhenFocusTarget(false);
        btnGuardadPPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardadPPlantaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProfesorPlantaLayout = new javax.swing.GroupLayout(panelProfesorPlanta);
        panelProfesorPlanta.setLayout(panelProfesorPlantaLayout);
        panelProfesorPlantaLayout.setHorizontalGroup(
            panelProfesorPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfesorPlantaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelProfesorPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProfesorPlantaLayout.createSequentialGroup()
                        .addGroup(panelProfesorPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfesorPlantaLayout.createSequentialGroup()
                                .addGroup(panelProfesorPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(1, 1, 1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProfesorPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spinnerFechaDeNombramiento)
                            .addComponent(txtCategoria)
                            .addComponent(txtValorDelPuntoSalarial)
                            .addComponent(txtNumeroDePuntosSalariales)))
                    .addGroup(panelProfesorPlantaLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroDeResolucionDeNombramiento, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardadPPlanta)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        panelProfesorPlantaLayout.setVerticalGroup(
            panelProfesorPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfesorPlantaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelProfesorPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelProfesorPlantaLayout.createSequentialGroup()
                        .addGroup(panelProfesorPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(spinnerFechaDeNombramiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProfesorPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNumeroDeResolucionDeNombramiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProfesorPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtNumeroDePuntosSalariales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProfesorPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtValorDelPuntoSalarial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProfesorPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnGuardadPPlanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelProfesorOcasional.setBorder(javax.swing.BorderFactory.createTitledBorder("Profesor Ocasional"));

        btnGuardarPOcasional.setText("GUARDAR");
        btnGuardarPOcasional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPOcasionalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProfesorOcasionalLayout = new javax.swing.GroupLayout(panelProfesorOcasional);
        panelProfesorOcasional.setLayout(panelProfesorOcasionalLayout);
        panelProfesorOcasionalLayout.setHorizontalGroup(
            panelProfesorOcasionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfesorOcasionalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardarPOcasional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelProfesorOcasionalLayout.setVerticalGroup(
            panelProfesorOcasionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfesorOcasionalLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(btnGuardarPOcasional)
                .addContainerGap())
        );

        panelProfesorCatedra.setBorder(javax.swing.BorderFactory.createTitledBorder("Porfesor de Catedra"));

        txtNumeroDeContratoSemestral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDeContratoSemestralActionPerformed(evt);
            }
        });

        jLabel14.setText("NUMERO DE CONTRATO SEMESTRAL");
        jLabel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setText("VALOR HORA");
        jLabel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setText("NUMERO DE HORAS QUE DICTA POR SEMANA");
        jLabel16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnGuardarPCatedra.setText("GUARDAR");
        btnGuardarPCatedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPCatedraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProfesorCatedraLayout = new javax.swing.GroupLayout(panelProfesorCatedra);
        panelProfesorCatedra.setLayout(panelProfesorCatedraLayout);
        panelProfesorCatedraLayout.setHorizontalGroup(
            panelProfesorCatedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfesorCatedraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelProfesorCatedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProfesorCatedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroDeHorasQueDictaPorSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroDeContratoSemestral, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarPCatedra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProfesorCatedraLayout.setVerticalGroup(
            panelProfesorCatedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfesorCatedraLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelProfesorCatedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardarPCatedra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelProfesorCatedraLayout.createSequentialGroup()
                        .addGroup(panelProfesorCatedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeroDeContratoSemestral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProfesorCatedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProfesorCatedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtNumeroDeHorasQueDictaPorSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        areaInformacion.setColumns(20);
        areaInformacion.setRows(5);
        areaInformacion.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORMACION"));
        jScrollPane1.setViewportView(areaInformacion);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORMACION GENERAL DE PROFESOR"));

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtNombre.setMinimumSize(new java.awt.Dimension(64, 30));
        txtNombre.setPreferredSize(new java.awt.Dimension(64, 30));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txCodigo.setMinimumSize(new java.awt.Dimension(64, 30));
        txCodigo.setPreferredSize(new java.awt.Dimension(64, 30));

        txtTituloAcademico.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtTituloAcademico.setPreferredSize(new java.awt.Dimension(64, 30));
        txtTituloAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloAcademicoActionPerformed(evt);
            }
        });

        txtDepartamento.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtDepartamento.setPreferredSize(new java.awt.Dimension(64, 30));

        txtSalarioBasico.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtSalarioBasico.setPreferredSize(new java.awt.Dimension(64, 30));
        txtSalarioBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioBasicoActionPerformed(evt);
            }
        });

        cmbTipoProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Catedra", "Planta", "Ocasional" }));
        cmbTipoProfesor.setToolTipText("");
        cmbTipoProfesor.setBorder(null);
        cmbTipoProfesor.setMinimumSize(new java.awt.Dimension(84, 22));
        cmbTipoProfesor.setPreferredSize(new java.awt.Dimension(64, 30));
        cmbTipoProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoProfesorActionPerformed(evt);
            }
        });
        cmbTipoProfesor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbTipoProfesorPropertyChange(evt);
            }
        });

        jLabel7.setText("TIPO");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel7.setPreferredSize(new java.awt.Dimension(64, 30));

        jLabel2.setText("NOMBRE");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setPreferredSize(new java.awt.Dimension(64, 30));

        jLabel3.setText("CODIGO");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setPreferredSize(new java.awt.Dimension(64, 30));

        jLabel4.setText("TITULO A.");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setPreferredSize(new java.awt.Dimension(64, 30));

        jLabel5.setText("DEPARTAMENTO");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setPreferredSize(new java.awt.Dimension(64, 30));

        jLabel6.setText("SALARIO BASICO");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setPreferredSize(new java.awt.Dimension(64, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDepartamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTituloAcademico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSalarioBasico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTipoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTituloAcademico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSalarioBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnInfoDocentes.setText("MOSTRAR INFORMACION DE DOCENTES");
        btnInfoDocentes.setToolTipText("");
        btnInfoDocentes.setEnabled(false);
        btnInfoDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoDocentesActionPerformed(evt);
            }
        });

        btnSalarioDocentes.setText("SALARIO PARA CADA DOCENTE");
        btnSalarioDocentes.setEnabled(false);
        btnSalarioDocentes.setMaximumSize(new java.awt.Dimension(201, 52));
        btnSalarioDocentes.setMinimumSize(new java.awt.Dimension(201, 52));
        btnSalarioDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalarioDocentesActionPerformed(evt);
            }
        });

        btnVinculacionDocentes.setText("TIPO DE VINCULACION DE DOCENTES");
        btnVinculacionDocentes.setEnabled(false);
        btnVinculacionDocentes.setMaximumSize(new java.awt.Dimension(233, 52));
        btnVinculacionDocentes.setMinimumSize(new java.awt.Dimension(233, 52));
        btnVinculacionDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVinculacionDocentesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(btnInfoDocentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalarioDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVinculacionDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelProfesorPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelProfesorOcasional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelProfesorCatedra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelProfesorPlanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelProfesorCatedra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelProfesorOcasional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalarioDocentes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnInfoDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVinculacionDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void cmbTipoProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoProfesorActionPerformed
        String seleccion = this.cmbTipoProfesor.getSelectedItem().toString();

        habilitarPanel(this.panelProfesorCatedra, seleccion.equalsIgnoreCase("catedra") || seleccion.equalsIgnoreCase("cátedra"));
        habilitarPanel(this.panelProfesorPlanta, seleccion.equalsIgnoreCase("planta"));
        habilitarPanel(this.panelProfesorOcasional, seleccion.equalsIgnoreCase("ocasional"));

        this.revalidate();
        this.repaint();


    }//GEN-LAST:event_cmbTipoProfesorActionPerformed

    private void cmbTipoProfesorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbTipoProfesorPropertyChange

    }//GEN-LAST:event_cmbTipoProfesorPropertyChange

    private void txtNumeroDePuntosSalarialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDePuntosSalarialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDePuntosSalarialesActionPerformed

    private void txtNumeroDeResolucionDeNombramientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDeResolucionDeNombramientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDeResolucionDeNombramientoActionPerformed

    private void txtTituloAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloAcademicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloAcademicoActionPerformed

    private void txtNumeroDeContratoSemestralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDeContratoSemestralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDeContratoSemestralActionPerformed

    private void btnGuardarPCatedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPCatedraActionPerformed

        try {
            String codigo = txCodigo.getText();
            String nombre = txtNombre.getText();
            String titulo = txtTituloAcademico.getText();
            String depto = txtDepartamento.getText();
            int salarioBasico = Integer.parseInt(txtSalarioBasico.getText());

            int numContrato = Integer.parseInt(txtNumeroDeContratoSemestral.getText());
            int horas = Integer.parseInt(txtNumeroDeHorasQueDictaPorSemana.getText());
            int valorHora = Integer.parseInt(txtValorHora.getText());

            

            this.areaInformacion.setText(myControlador.registrarDocenteCatedra(codigo, nombre, titulo, depto, salarioBasico, numContrato, horas, valorHora));
            limpiarCamposGenerales();
            limpiarCamposEspecificos();
            activarBotonesReporte();
        } catch (NumberFormatException e) {
            this.areaInformacion.setText("Por favor verifique los campos numéricos. Error de ingreso");
        }
    }//GEN-LAST:event_btnGuardarPCatedraActionPerformed

    private void txtSalarioBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioBasicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioBasicoActionPerformed

    private void btnInfoDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoDocentesActionPerformed
        this.areaInformacion.setText(myControlador.obtenerInformacionTodos());        // TODO add your handling code here:
    }//GEN-LAST:event_btnInfoDocentesActionPerformed

    private void btnSalarioDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalarioDocentesActionPerformed
        this.areaInformacion.setText(myControlador.obtenerSalariosCalculados());
    }//GEN-LAST:event_btnSalarioDocentesActionPerformed

    private void btnGuardadPPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardadPPlantaActionPerformed

        try {
            String codigo = txCodigo.getText();
            String nombre = txtNombre.getText();
            String titulo = txtTituloAcademico.getText();
            String depto = txtDepartamento.getText();
            int salarioBasico = Integer.parseInt(txtSalarioBasico.getText());

            int puntos = Integer.parseInt(txtNumeroDePuntosSalariales.getText());
            int valorPunto = Integer.parseInt(txtValorDelPuntoSalarial.getText());
            String categoria = txtCategoria.getText();
            int numRes = Integer.parseInt(txtNumeroDeResolucionDeNombramiento.getText());

            java.util.Date date = (java.util.Date) spinnerFechaDeNombramiento.getValue();
            java.time.LocalDateTime fecha = date.toInstant()
                    .atZone(java.time.ZoneId.systemDefault())
                    .toLocalDateTime();

            

            this.areaInformacion.setText(myControlador.registrarDocentePlanta(codigo, nombre, titulo, depto, salarioBasico, puntos, valorPunto, categoria, numRes, fecha));
            limpiarCamposGenerales();
            limpiarCamposEspecificos();
            activarBotonesReporte();
        } catch (NumberFormatException e) {
            this.areaInformacion.setText("Por favor verifique los campos numéricos. Error de ingreso");
        }

    }//GEN-LAST:event_btnGuardadPPlantaActionPerformed

    private void btnGuardarPOcasionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPOcasionalActionPerformed

        try {
            String codigo = txCodigo.getText();
            String nombre = txtNombre.getText();
            String titulo = txtTituloAcademico.getText();
            String depto = txtDepartamento.getText();
            int salarioBasico = Integer.parseInt(txtSalarioBasico.getText());

            

            this.areaInformacion.setText(myControlador.registrarDocenteOcasional(codigo, nombre, titulo, depto, salarioBasico));
            limpiarCamposGenerales();
            limpiarCamposEspecificos();
            activarBotonesReporte();
        } catch (NumberFormatException e) {
            this.areaInformacion.setText("Por favor verifique los campos numéricos.  Error de ingreso");

}    }//GEN-LAST:event_btnGuardarPOcasionalActionPerformed

    private void btnVinculacionDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVinculacionDocentesActionPerformed
        this.areaInformacion.setText(myControlador.obtenerTiposVinculacionTodos());        // TODO add your handling code here:
    }//GEN-LAST:event_btnVinculacionDocentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaGeneral().setVisible(true);
            }
        });

    }

    private void habilitarPanel(javax.swing.JPanel panel, boolean estado) {
        panel.setEnabled(estado);
        limpiarCamposEspecificos();
        for (java.awt.Component c : panel.getComponents()) {
            c.setEnabled(estado);
        }
    }

    public void limpiarCamposGenerales() {
        this.txCodigo.setText("");
        this.txtNombre.setText("");
        this.txtSalarioBasico.setText("");
        this.txtTituloAcademico.setText("");
        this.txtDepartamento.setText("");
    }

    public void limpiarCamposEspecificos() {

        this.txtNumeroDeContratoSemestral.setText("");
        this.txtNumeroDeHorasQueDictaPorSemana.setText("");
        this.txtValorHora.setText("");

        this.txtNumeroDePuntosSalariales.setText("");
        this.txtValorDelPuntoSalarial.setText("");
        this.txtCategoria.setText("");
        this.txtNumeroDeResolucionDeNombramiento.setText("");
    }

    private void activarBotonesReporte() {
        this.btnInfoDocentes.setEnabled(true);
        this.btnSalarioDocentes.setEnabled(true);
        this.btnVinculacionDocentes.setEnabled(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaInformacion;
    private javax.swing.JButton btnGuardadPPlanta;
    private javax.swing.JButton btnGuardarPCatedra;
    private javax.swing.JButton btnGuardarPOcasional;
    private javax.swing.JButton btnInfoDocentes;
    private javax.swing.JButton btnSalarioDocentes;
    private javax.swing.JButton btnVinculacionDocentes;
    private javax.swing.JComboBox<String> cmbTipoProfesor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelProfesorCatedra;
    private javax.swing.JPanel panelProfesorOcasional;
    private javax.swing.JPanel panelProfesorPlanta;
    private javax.swing.JSpinner spinnerFechaDeNombramiento;
    private javax.swing.JTextField txCodigo;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroDeContratoSemestral;
    private javax.swing.JTextField txtNumeroDeHorasQueDictaPorSemana;
    private javax.swing.JTextField txtNumeroDePuntosSalariales;
    private javax.swing.JTextField txtNumeroDeResolucionDeNombramiento;
    private javax.swing.JTextField txtSalarioBasico;
    private javax.swing.JTextField txtTituloAcademico;
    private javax.swing.JTextField txtValorDelPuntoSalarial;
    private javax.swing.JTextField txtValorHora;
    // End of variables declaration//GEN-END:variables
}
